# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: user.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'user.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from google.protobuf import field_mask_pb2 as google_dot_protobuf_dot_field__mask__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nuser.proto\x12\x07user.v1\x1a\x1bgoogle/protobuf/empty.proto\x1a google/protobuf/field_mask.proto\"\x1c\n\x0eGetUserRequest\x12\n\n\x02id\x18\x01 \x01(\t\"X\n\x11\x43reateUserRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\r\n\x05\x65mail\x18\x02 \x01(\t\x12&\n\x08location\x18\x03 \x01(\x0b\x32\x14.user.v1.Geolocation\"a\n\x11UpdateUserRequest\x12\x1b\n\x04user\x18\x01 \x01(\x0b\x32\r.user.v1.User\x12/\n\x0bupdate_mask\x18\x02 \x01(\x0b\x32\x1a.google.protobuf.FieldMask\"\x1f\n\x11\x44\x65leteUserRequest\x12\n\n\x02id\x18\x01 \x01(\t\"W\n\x04User\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\r\n\x05\x65mail\x18\x03 \x01(\t\x12&\n\x08location\x18\x04 \x01(\x0b\x32\x14.user.v1.Geolocation\"2\n\x0bGeolocation\x12\x10\n\x08latitude\x18\x01 \x01(\x01\x12\x11\n\tlongitude\x18\x02 \x01(\x01\x32\xf4\x01\n\x0bUserService\x12\x37\n\nCreateUser\x12\x1a.user.v1.CreateUserRequest\x1a\r.user.v1.User\x12\x31\n\x07GetUser\x12\x17.user.v1.GetUserRequest\x1a\r.user.v1.User\x12\x37\n\nUpdateUser\x12\x1a.user.v1.UpdateUserRequest\x1a\r.user.v1.User\x12@\n\nDeleteUser\x12\x1a.user.v1.DeleteUserRequest\x1a\x16.google.protobuf.Emptyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'user_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GETUSERREQUEST']._serialized_start=86
  _globals['_GETUSERREQUEST']._serialized_end=114
  _globals['_CREATEUSERREQUEST']._serialized_start=116
  _globals['_CREATEUSERREQUEST']._serialized_end=204
  _globals['_UPDATEUSERREQUEST']._serialized_start=206
  _globals['_UPDATEUSERREQUEST']._serialized_end=303
  _globals['_DELETEUSERREQUEST']._serialized_start=305
  _globals['_DELETEUSERREQUEST']._serialized_end=336
  _globals['_USER']._serialized_start=338
  _globals['_USER']._serialized_end=425
  _globals['_GEOLOCATION']._serialized_start=427
  _globals['_GEOLOCATION']._serialized_end=477
  _globals['_USERSERVICE']._serialized_start=480
  _globals['_USERSERVICE']._serialized_end=724
# @@protoc_insertion_point(module_scope)
