apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}
  annotations:
    konghq.com/protocol: grpc
  labels:
    app: {{ .Chart.Name }}
spec:
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
  selector:
    app: {{ .Chart.Name }}